apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: esindex-operator-rolebinding
  labels:
    app.kubernetes.io/name: esindex-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: esindex-operator-role
subjects:
- kind: ServiceAccount
  name: esindex-operator
  namespace: default
