apiVersion: ibmcloud.ibm.com/v1alpha1
kind: EsIndex
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: index16
spec:
  esURIComposed:
    configMapKeyRef: 
      name: test-es-configmap
      key: es-uri
  indexName: rainbow
  numberOfShards: 2
  numberOfReplicas: 1