apiVersion:  apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/name: esindex-operator 
  name: esindex-operator
  namespace: ibmcloud-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esindex-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esindex-operator
    spec:
      containers:
      - args:
        - "-logtostderr=true"
        - "-v=5"
        command:
        - ./manager
        image: PLACEHOLDER
        imagePullPolicy: Always
        name: esindex-controller
      serviceAccountName: esindex-operator